### ISSUE TITLE
Detection Benchmark

### ISSUE THREAD

**Issue by seekingdeep** [ThiruRJST/Deformed-Yolo#1]
@ThiruRJST Hi there,
what is the current detection results on [SROIE](https://rrc.cvc.uab.es/?ch=13), [ICDAR2015](https://rrc.cvc.uab.es/?ch=4)
Recall | Precision | Hmean

**Comment by ThiruRJST** [comment]
@seekingdeep Hi,
I haven't built the model yet because have some issues related to using Deformable Convolutions which makes the model more unstable while training.  I'm working on the backbone more since that's the thing that changes performances.
